{% set name = "icet" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc0757874042644b8a2bbbd6bde41cbfe4d8c024659cfcc9a7d66e3a1eb167a9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - ase
    - pandas
    - numpy <1.21
    - scipy
    - scikit-learn
    - spglib
    - boost
    - pybind11
    - eigen
  run:
    - python
    - pip
    - pybind11
    - ase
    - pandas
    - numpy <1.21
    - scikit-learn
    - spglib
    - numba
    - trainstation

test:
  imports:
    - icet
  commands:
    - pip check

about:
  home: https://icet.materialsmodeling.org
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: icet — A Pythonic approach to cluster expansions

  description: |
    icet is a tool for the construction and sampling of alloy cluster 
    expansions.
  doc_url: https://icet.materialsmodeling.org
  dev_url: https://gitlab.com/materials-modeling/icet

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
    - rozyczko
