{% set name = "icet" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc0757874042644b8a2bbbd6bde41cbfe4d8c024659cfcc9a7d66e3a1eb167a9

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - ase
    - numba
    - numpy
    - pandas >=0.23
    - python
    - scipy
    - spglib >1.12.0
    - trainstation >=0.2

test:
  imports:
    - icet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://icet.materialsmodeling.org
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: icet — A Pythonic approach to cluster expansions

  description: |
    icet is a tool for the construction and sampling of alloy cluster 
    expansions.
  doc_url: https://icet.materialsmodeling.org
  dev_url: https://gitlab.com/materials-modeling/icet

extra:
  recipe-maintainers:
    - jan-janssen
    - erhart1
    - rozyczko
