travis:
  secure:
    BINSTAR_TOKEN: uZbCdqVtq0lQQ0UpIhwiZ/x4gdKqP6dLPk2bSDvqYs2x6cG6VXjgDEpjW9TXG+b8BP1pRdXf8FvRLZvfF41M2YzbwpgqzedNo5aOAuz3HVzltTL+apT1NbcmxPG/Ii6cfGgxnWzAnqEJNQrnW5zGhQCPT2W2xmkUVR5CxQA5P5e/5p96J0NtxtZo+eAaipVTtdCu+loa3kHT7IkmkThrhM+xILf8SZPievdAPC0zCcm36XEL+S58J5nARw6xIlrNl0du+SlNL2Gjknb/73UkUu7tmwJ/47ppmBemM8BkFmgV1nze924KKKgnJaxqqvALRpAC0PvoZKKO/FV2KtK6dedJKm8JU8W/gQcKJtM0JnRzeYIhu0S3CObhxYVKhQHSRbyLuZi/8qNFwVG7v4LKq49Ezl5F7eaL1rodrjbXtdKEJRzIGDezrIXECezpeq2aW190Zplcn1ms+0A3J4dp5iCZta5M6CQq/rhRW+Br2vaZaoO+jBqBSq7KdzSS14Vfc4nVDtGWThmA5eCGR+0PTGADfSD2TS1HgpP48Cg8XoFR9rfxXxFV48Mqbv0mt3cQbNmhac/qCf8N5zo56QwfPYZ4s4PgfcocYJdyJSUb7sbeIqPhN2CvFmIg6nDxaHq0dg3Lk4mzVnNa2EtrdabqcyLXzC93Uqpiaa0ukZ7jKNM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
